services:
  - type: web
    name: KrishPetRec
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.api:app --host=0.0.0.0 --port=10000
    runtime: python
    pythonVersion: 3.10.13
